# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [239]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))



#asking for a dimension of the matrix
ok = False
while not ok:
    try:
        dimension = int(input('Enter matrix dimension: '))
        ok = True
    except:
        print('Value isn\'t positive integer, try again')
matrix_1 = random_matrix(dimension)
print(matrix_1,'\n')

#function #1 defines all the permutations of elements, it also sets a sign for a permutation for the next multiplication process
def permutations(matrix):
    permutations = []
    current_permutation = []
    list_of_indexes = list(itertools.permutations([a for a in range(dimension)],dimension))      #list of all index permutations
    for variant in list(list_of_indexes):        
        permutation_is_odd = 0       
        for i in variant:                                                    #finding oddity of every permutation to calculate it's sign
            if variant.index(i) != (dimension-1):
                for m in range(variant.index(i),dimension):
                    if variant[variant.index(i)] - variant[m] > 0:
                        permutation_is_odd += 1        
        if permutation_is_odd % 2 == 0:                     #adding sign to the permutation (changing it from "positive" if it's the case)
            current_permutation = ['positive']
            for a in variant:
                current_permutation.append(int(matrix[variant.index(a),a]))
        else:
            current_permutation = ['negative']
            for a in variant:
                current_permutation.append(int(matrix[variant.index(a),a]))
        permutations.append(list(current_permutation))
    return permutations

#function #2 takes a list of number lists with first elements defining the sign of the result
def multiplications(list_of_permutations):
    list_of_multiplications = []
    for permutation in list_of_permutations:
        d = 1
        if permutation[0] == 'negative':
            for elem in permutation[1:]:
                d *= elem
            list_of_multiplications.append(-d)
        else:
            for elem in permutation[1:]:
                d *= elem
            list_of_multiplications.append(d)
    return list_of_multiplications

#this one simply sums all of elements in the list
def sum_of_things(list_of_things):
    det = 0
    for item in list_of_things:
        det += item
    return det

print(f'My determinant is {sum_of_things(multiplications(permutations(matrix_1)))}')
print(f'While the real one is {round(np.linalg.det(matrix_1))}')
print('As you can see, they\'re equal, and if they aren\'t, this is a witchery')

[[9 3 3 0 0 8 0 5]
 [7 4 1 5 4 0 8 9]
 [7 4 6 6 7 9 5 8]
 [8 5 3 8 0 0 0 0]
 [2 7 2 7 4 7 4 5]
 [7 3 3 1 3 0 9 6]
 [4 4 2 3 4 0 8 2]
 [1 6 9 3 4 4 9 8]] 

My determinant is -848839
While the real one is -848839
As you can see, they're equal, and if they aren't, this is a witchery
